import { spawn } from "node:child_process";
import type { ToolDefinition } from "../../core/types.js";
import { killProcessGroup } from "../../util/process.js";
import { runSsh, buildSshArgs, type SshResult } from "./remote-exec.js";

// Real, standalone remote deploy/rollback — a symlink-based release
// pattern (the same one Capistrano, and this maintainer's own personal
// deploy.py, use): each deploy lands in its own timestamped directory
// under releasesDir/, and a `current` symlink is only re-pointed at it
// after a health check passes, atomically, so a previous release is
// never destroyed and rollback is just re-pointing the symlink back.
// Wraps the real `ssh`/`rsync` CLIs (same "wrap the real, versioned
// client" stance as run_docker/run_kubectl/argocd.ts) rather than adding
// an SSH npm dependency — auth is entirely the user's own already-
// configured key-based SSH (agent or ~/.ssh/config IdentityFile), the
// same "not this tool's job to manage auth" stance run_kubectl takes
// about the ambient kubeconfig. No password param exists anywhere here,
// on purpose — key-based auth only.
const DEFAULT_TIMEOUT_MS = 120_000;
const DEFAULT_HEALTH_CHECK_TIMEOUT_MS = 30_000;
const DEFAULT_KEEP_RELEASES = 5;

// --- Injection safety -----------------------------------------------
//
// Every command below is built as a STRING because ssh's own argv
// contract requires the remote command as one final argv element (see
// remote-exec.ts's buildSshArgs) — that string is handed to the REMOTE
// shell, not the local one, so there is no local re-tokenization hazard
// the way runSubprocess's shell:true would create. The hazard here is
// narrower but real: `host`, `user`, `releasesDir`, and `currentSymlink`
// are all spliced directly into remote command strings THIS module
// constructs (mkdir/ln/mv/ls/readlink/rm), so a value like
// `; rm -rf /` in any of them would run as a second command on the
// remote host, not just get treated as a literal path. Unlike
// `startCommand`/`healthCheckCommand` — which are deliberately
// arbitrary, user-authored remote shell commands, exactly like
// run_remote_command's own `command` field — these four fields are
// supposed to be plain identifiers/paths, never shell syntax, so instead
// of trying to quote/escape them (easy to get subtly wrong: nested
// quotes, `$()`, backticks all survive naive single-quoting) we just
// reject any value containing a shell metacharacter outright. A
// rejected deploy is safe; a "cleverly escaped" one is not worth the
// risk.
const SHELL_METACHARACTERS = /[;&|$`\n]/;

function assertSafe(value: string, fieldName: string): void {
  if (value.length === 0) throw new Error(`${fieldName} must not be empty`);
  if (SHELL_METACHARACTERS.test(value)) {
    throw new Error(`${fieldName} contains a shell metacharacter (; & | $ \` or a newline) and was rejected, this field must be a plain identifier/path, not shell syntax`);
  }
}

// Release directory names are generated by this module, never by the
// caller (unlike releasesDir/currentSymlink) — but remote_list_releases
// and the pruning step both read directory names BACK off the remote
// host via `ls`, so this pattern re-validates that untrusted round-trip
// before splicing any of those names into a further rm/ln command.
const RELEASE_NAME_PATTERN = /^[0-9TZ-]+$/;

function releaseTimestampName(): string {
  // ISO timestamp with `:`/`.` swapped for `-` — safe as a path segment
  // on every common filesystem, and still lexicographically sortable in
  // chronological order (RELEASE_NAME_PATTERN's charset matches exactly
  // this format).
  return new Date().toISOString().replace(/[:.]/g, "-");
}

export interface RemoteDeployToolOptions {
  sshBinary?: string;
  rsyncBinary?: string;
}

function runLocal(command: string, args: string[], timeoutMs: number): Promise<SshResult> {
  // Same shape as remote-exec.ts's runSsh (spawn with a real argv array,
  // shell:false — the default — so rsync's own args are never
  // re-tokenized by a local shell), reimplemented here only because
  // runSsh is ssh-specific in name/comments; the mechanics are identical.
  return new Promise((resolve) => {
    const child = spawn(command, args, { detached: true });
    let stdout = "";
    let stderr = "";
    let timedOut = false;
    const timer = setTimeout(() => {
      timedOut = true;
      killProcessGroup(child);
    }, timeoutMs);
    child.stdout?.on("data", (d) => (stdout += d));
    child.stderr?.on("data", (d) => (stderr += d));
    child.on("close", (code) => {
      clearTimeout(timer);
      resolve({ stdout, stderr: timedOut ? `Timed out after ${timeoutMs}ms` : stderr, isError: timedOut || code !== 0, exitCode: timedOut ? null : code });
    });
    child.on("error", (err) => {
      clearTimeout(timer);
      resolve({ stdout: "", stderr: err.message, isError: true, exitCode: null });
    });
  });
}

interface Target {
  host: string;
  user: string;
  releasesDir: string;
  currentSymlink: string;
}

function validateTarget(t: Target): void {
  assertSafe(t.host, "host");
  assertSafe(t.user, "user");
  assertSafe(t.releasesDir, "releasesDir");
  assertSafe(t.currentSymlink, "currentSymlink");
}

async function ssh(binary: string, target: Target, command: string, timeoutMs: number): Promise<SshResult> {
  return runSsh(binary, buildSshArgs({ host: target.host, user: target.user, command }), timeoutMs);
}

/** Atomic symlink swap — `ln -sfn` creates the new symlink next to (not replacing) the live one, then `mv -Tf` (rename(2) under the hood, atomic on the same filesystem — true here since tmp and real both live directly under currentSymlink's own parent dir) flips it into place in one step, so nothing ever observes a missing/half-updated symlink. */
function swapCommand(target: Target, releasePath: string): string {
  const tmp = `${target.currentSymlink}.tmp`;
  return `ln -sfn ${releasePath} ${tmp} && mv -Tf ${tmp} ${target.currentSymlink}`;
}

async function readCurrentReleasePath(binary: string, target: Target, timeoutMs: number): Promise<string | undefined> {
  const result = await ssh(binary, target, `readlink ${target.currentSymlink} 2>/dev/null || true`, timeoutMs);
  const path = result.stdout.trim();
  return path.length > 0 ? path : undefined;
}

async function listReleaseNames(binary: string, target: Target, timeoutMs: number): Promise<string[]> {
  const result = await ssh(binary, target, `ls -1 ${target.releasesDir} 2>/dev/null || true`, timeoutMs);
  return result.stdout
    .split("\n")
    .map((line) => line.trim())
    .filter((name) => name.length > 0 && RELEASE_NAME_PATTERN.test(name))
    .sort();
}

// --- remote_deploy_release --------------------------------------------

interface RemoteDeployReleaseInput {
  host: string;
  user: string;
  releasesDir: string;
  currentSymlink: string;
  localArtifactPath: string;
  startCommand?: string;
  healthCheckCommand?: string;
  healthCheckTimeoutMs?: number;
  keepReleases?: number;
  timeoutMs?: number;
}

function createRemoteDeployReleaseTool(sshBinary: string, rsyncBinary: string): ToolDefinition<RemoteDeployReleaseInput> {
  return {
    name: "remote_deploy_release",
    description:
      "Deploy a local build artifact to a remote host using a real, standard symlink-based release pattern " +
      "(the same one Capistrano-style deploy tools use): rsyncs localArtifactPath into a new timestamped " +
      "directory under releasesDir, then atomically re-points currentSymlink at it only after startCommand/" +
      "healthCheckCommand (if given) succeed, a previous release is never touched, so a bad deploy is a symlink " +
      "flip away from being undone. If healthCheckCommand fails, the symlink is automatically rolled back to the " +
      "previous release and this reports isError with a clear message naming the rollback target. Auth is " +
      "entirely the user's own existing key-based SSH setup (ssh-agent or ~/.ssh/config), this tool takes no " +
      "password and never will. " +
      "IMPORTANT: this changes real state on a real remote host, confirm with the user before running it unless " +
      "they've explicitly asked for this exact deploy.",
    riskLevel: "ask",
    riskKey: (input) => `remote_deploy_release:${input.host}`,
    inputSchema: {
      type: "object",
      properties: {
        host: { type: "string", description: "Hostname or IP of the remote target (not a ~/.ssh/config alias containing spaces/metacharacters)" },
        user: { type: "string", description: "Remote SSH username" },
        releasesDir: { type: "string", description: "Remote directory holding one subdirectory per release, e.g. /srv/myapp/releases" },
        currentSymlink: { type: "string", description: "Remote path of the 'current' symlink, e.g. /srv/myapp/current" },
        localArtifactPath: { type: "string", description: "Local directory to rsync into the new release directory" },
        startCommand: { type: "string", description: "Optional command run over ssh from inside the new release directory, e.g. a service restart" },
        healthCheckCommand: {
          type: "string",
          description: "Optional command run over ssh from inside the new release directory; a nonzero exit rolls the symlink back to the previous release automatically",
        },
        healthCheckTimeoutMs: { type: "number", description: `Timeout for healthCheckCommand in milliseconds (default ${DEFAULT_HEALTH_CHECK_TIMEOUT_MS})` },
        keepReleases: { type: "number", description: `How many recent release directories to keep; older ones are pruned, except the current and previous (rollback target) (default ${DEFAULT_KEEP_RELEASES})` },
        timeoutMs: { type: "number", description: `Timeout for rsync/ssh setup steps in milliseconds (default ${DEFAULT_TIMEOUT_MS})` },
      },
      required: ["host", "user", "releasesDir", "currentSymlink", "localArtifactPath"],
    },
    describeCall: (input) =>
      `deploy ${input.localArtifactPath} to ${input.user}@${input.host}:${input.releasesDir} ` +
      `(${input.healthCheckCommand ? "health-checked, auto-rollback on failure" : "no health check"})`,
    async handler(input) {
      const target: Target = { host: input.host, user: input.user, releasesDir: input.releasesDir, currentSymlink: input.currentSymlink };
      try {
        validateTarget(target);
      } catch (err) {
        return { content: (err as Error).message, isError: true };
      }
      if (input.localArtifactPath.length === 0) return { content: "localArtifactPath must not be empty", isError: true };

      const timeoutMs = input.timeoutMs ?? DEFAULT_TIMEOUT_MS;
      const healthCheckTimeoutMs = input.healthCheckTimeoutMs ?? DEFAULT_HEALTH_CHECK_TIMEOUT_MS;
      const keepReleases = input.keepReleases ?? DEFAULT_KEEP_RELEASES;
      const release = releaseTimestampName();
      const releasePath = `${target.releasesDir}/${release}`;

      // Previous release, captured BEFORE the swap, so a failed health
      // check has something concrete to roll back to.
      const previousReleasePath = await readCurrentReleasePath(sshBinary, target, timeoutMs);

      const mkdir = await ssh(sshBinary, target, `mkdir -p ${target.releasesDir}`, timeoutMs);
      if (mkdir.isError) return { content: `Failed to prepare ${target.releasesDir} on ${target.host}: ${mkdir.stderr}`, isError: true };

      // Real rsync flags: -a (archive: recursive + preserves perms/times/
      // symlinks), -z (compress in transit). Trailing slash on the SOURCE
      // copies its CONTENTS into the destination (rather than nesting a
      // same-named directory inside it) — standard rsync trailing-slash
      // semantics. `-e "ssh -o BatchMode=yes"` keeps this transport
      // non-interactive, matching every other ssh call here (BatchMode
      // fails fast instead of hanging on a password prompt). rsync
      // creates the new leaf release directory itself as part of the
      // transfer as long as its PARENT (releasesDir, mkdir -p'd above)
      // already exists — no separate remote mkdir of the release dir
      // itself needed.
      const rsyncArgs = ["-az", "-e", `${sshBinary} -o BatchMode=yes`, `${input.localArtifactPath}/`, `${target.user}@${target.host}:${releasePath}/`];
      const rsync = await runLocal(rsyncBinary, rsyncArgs, timeoutMs);
      if (rsync.isError) return { content: `rsync to ${target.host} failed: ${rsync.stderr}`, isError: true };

      const swap = await ssh(sshBinary, target, swapCommand(target, releasePath), timeoutMs);
      if (swap.isError) return { content: `Deployed ${release} but failed to flip ${target.currentSymlink}: ${swap.stderr}`, isError: true };

      if (input.startCommand) {
        const start = await ssh(sshBinary, target, `cd ${releasePath} && ${input.startCommand}`, timeoutMs);
        if (start.isError) {
          // startCommand itself failed — the symlink already points at
          // the new (apparently broken) release. Roll back the same way
          // a failed health check would, since a start failure is at
          // least as strong a signal something is wrong.
          if (previousReleasePath) await ssh(sshBinary, target, swapCommand(target, previousReleasePath), timeoutMs);
          const rollbackNote = previousReleasePath ? `, rolled back to ${previousReleasePath}` : ", no previous release to roll back to";
          return { content: `Deployed ${release} but startCommand failed${rollbackNote}: ${start.stderr}`, isError: true };
        }
      }

      if (input.healthCheckCommand) {
        const health = await ssh(sshBinary, target, `cd ${releasePath} && ${input.healthCheckCommand}`, healthCheckTimeoutMs);
        if (health.isError) {
          if (previousReleasePath) {
            const rollback = await ssh(sshBinary, target, swapCommand(target, previousReleasePath), timeoutMs);
            if (rollback.isError) {
              return { content: `Deployed ${release} but health check failed AND automatic rollback also failed: ${rollback.stderr}`, isError: true };
            }
            return { content: `Deployed ${release} but health check failed, rolled back to ${previousReleasePath}. Health check output: ${health.stderr || health.stdout}`, isError: true };
          }
          return { content: `Deployed ${release} but health check failed, no previous release to roll back to. Health check output: ${health.stderr || health.stdout}`, isError: true };
        }
      }

      const pruneNote = await pruneOldReleases(sshBinary, target, timeoutMs, keepReleases, release, previousReleasePath);
      return { content: `Deployed and switched ${target.currentSymlink} -> ${releasePath} on ${target.host}.${pruneNote}`, isError: false };
    },
  };
}

/** Deletes release directories beyond the most recent `keepReleases`, always sparing the just-deployed release and whatever was previous (rollback target) even if that pushes it outside the count. */
async function pruneOldReleases(binary: string, target: Target, timeoutMs: number, keepReleases: number, currentRelease: string, previousReleasePath: string | undefined): Promise<string> {
  const names = await listReleaseNames(binary, target, timeoutMs);
  if (names.length <= keepReleases) return "";

  const previousName = previousReleasePath?.split("/").pop();
  const keep = new Set(names.slice(-keepReleases));
  keep.add(currentRelease);
  if (previousName) keep.add(previousName);

  const toPrune = names.filter((name) => !keep.has(name) && RELEASE_NAME_PATTERN.test(name));
  if (toPrune.length === 0) return "";

  const paths = toPrune.map((name) => `${target.releasesDir}/${name}`).join(" ");
  const prune = await ssh(binary, target, `rm -rf ${paths}`, timeoutMs);
  if (prune.isError) return ` (pruning old releases failed: ${prune.stderr})`;
  return ` Pruned ${toPrune.length} old release(s).`;
}

// --- remote_rollback_release -------------------------------------------

interface RemoteRollbackReleaseInput {
  host: string;
  user: string;
  releasesDir: string;
  currentSymlink: string;
  timeoutMs?: number;
}

function createRemoteRollbackReleaseTool(sshBinary: string): ToolDefinition<RemoteRollbackReleaseInput> {
  return {
    name: "remote_rollback_release",
    description:
      "Roll a symlink-based deploy (see remote_deploy_release) back to the release directory immediately before " +
      "the one currentSymlink currently points at, same atomic ln -sfn/mv symlink swap, no rsync/build step.",
    riskLevel: "ask",
    riskKey: () => "remote_rollback_release",
    inputSchema: {
      type: "object",
      properties: {
        host: { type: "string" },
        user: { type: "string" },
        releasesDir: { type: "string" },
        currentSymlink: { type: "string" },
        timeoutMs: { type: "number", description: `Timeout in milliseconds (default ${DEFAULT_TIMEOUT_MS})` },
      },
      required: ["host", "user", "releasesDir", "currentSymlink"],
    },
    describeCall: (input) => `roll back ${input.currentSymlink} on ${input.user}@${input.host}`,
    async handler(input) {
      const target: Target = { host: input.host, user: input.user, releasesDir: input.releasesDir, currentSymlink: input.currentSymlink };
      try {
        validateTarget(target);
      } catch (err) {
        return { content: (err as Error).message, isError: true };
      }
      const timeoutMs = input.timeoutMs ?? DEFAULT_TIMEOUT_MS;

      const names = await listReleaseNames(sshBinary, target, timeoutMs);
      if (names.length === 0) return { content: `No release directories found under ${target.releasesDir} on ${target.host}.`, isError: true };

      const currentPath = await readCurrentReleasePath(sshBinary, target, timeoutMs);
      const currentName = currentPath?.split("/").pop();
      const currentIndex = currentName ? names.indexOf(currentName) : -1;

      const previousIndex = currentIndex === -1 ? names.length - 2 : currentIndex - 1;
      if (previousIndex < 0) {
        return { content: `No release before ${currentName ?? "the current one"} to roll back to on ${target.host}.`, isError: true };
      }

      const previousName = names[previousIndex];
      const previousPath = `${target.releasesDir}/${previousName}`;
      const swap = await ssh(sshBinary, target, swapCommand(target, previousPath), timeoutMs);
      if (swap.isError) return { content: `Rollback of ${target.currentSymlink} on ${target.host} failed: ${swap.stderr}`, isError: true };

      return { content: `Rolled ${target.currentSymlink} back to ${previousPath} on ${target.host}.`, isError: false };
    },
  };
}

// --- remote_list_releases ------------------------------------------------

interface RemoteListReleasesInput {
  host: string;
  user: string;
  releasesDir: string;
  currentSymlink?: string;
  timeoutMs?: number;
}

function createRemoteListReleasesTool(sshBinary: string): ToolDefinition<RemoteListReleasesInput> {
  return {
    name: "remote_list_releases",
    description: "List release directories under releasesDir on a remote host (see remote_deploy_release), marking which one currentSymlink points at, if given. Read-only.",
    riskLevel: "safe",
    inputSchema: {
      type: "object",
      properties: {
        host: { type: "string" },
        user: { type: "string" },
        releasesDir: { type: "string" },
        currentSymlink: { type: "string", description: "Optional, if given, the listing marks the currently-active release" },
        timeoutMs: { type: "number", description: `Timeout in milliseconds (default ${DEFAULT_TIMEOUT_MS})` },
      },
      required: ["host", "user", "releasesDir"],
    },
    describeCall: (input) => `list releases under ${input.releasesDir} on ${input.user}@${input.host}`,
    async handler(input) {
      const target: Target = { host: input.host, user: input.user, releasesDir: input.releasesDir, currentSymlink: input.currentSymlink ?? "" };
      try {
        assertSafe(target.host, "host");
        assertSafe(target.user, "user");
        assertSafe(target.releasesDir, "releasesDir");
        if (input.currentSymlink) assertSafe(input.currentSymlink, "currentSymlink");
      } catch (err) {
        return { content: (err as Error).message, isError: true };
      }
      const timeoutMs = input.timeoutMs ?? DEFAULT_TIMEOUT_MS;

      const names = await listReleaseNames(sshBinary, target, timeoutMs);
      if (names.length === 0) return { content: `No release directories found under ${target.releasesDir} on ${target.host}.`, isError: false };

      let currentName: string | undefined;
      if (input.currentSymlink) {
        const currentPath = await readCurrentReleasePath(sshBinary, target, timeoutMs);
        currentName = currentPath?.split("/").pop();
      }

      const lines = names.map((name) => (name === currentName ? `${name} (current)` : name));
      return { content: lines.join("\n"), isError: false };
    },
  };
}

export function createRemoteDeployTools(options: RemoteDeployToolOptions = {}): ToolDefinition[] {
  const sshBinary = options.sshBinary ?? "ssh";
  const rsyncBinary = options.rsyncBinary ?? "rsync";
  return [createRemoteDeployReleaseTool(sshBinary, rsyncBinary), createRemoteRollbackReleaseTool(sshBinary), createRemoteListReleasesTool(sshBinary)];
}
